# Generated by Django 5.0.6 on 2026-07-04 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('alert_type', models.CharField(choices=[('BELOW_TARGET', 'Price Below Target'), ('ABOVE_TARGET', 'Price Above Target'), ('BACK_IN_STOCK', 'Back In Stock'), ('OUT_OF_STOCK', 'Out Of Stock'), ('DISCOUNT_INCREASED', 'Discount Increased')], default='BELOW_TARGET', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIGGERED', 'Triggered'), ('EXPIRED', 'Expired'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('merchant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='merchant_products.merchantproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
