# Generated by Django 5.0.6 on 2026-07-04 05:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_product_url', models.URLField(max_length=500)),
                ('merchant_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliate_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('availability_status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('LIMITED_STOCK', 'Limited Stock'), ('OUT_OF_STOCK', 'Out Of Stock'), ('COMING_SOON', 'Coming Soon'), ('DISCONTINUED', 'Discontinued')], default='IN_STOCK', max_length=20)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estimated_delivery_days', models.IntegerField(blank=True, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cashback_available', models.BooleanField(default=False)),
                ('emi_available', models.BooleanField(default=False)),
                ('cod_available', models.BooleanField(default=False)),
                ('exchange_available', models.BooleanField(default=False)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_listings', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_products', to='stores.store')),
            ],
            options={
                'ordering': ['current_price'],
                'unique_together': {('product', 'store')},
            },
        ),
    ]
