# Generated by Django 5.0.6 on 2026-07-04 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_product_url', models.URLField(max_length=1000)),
                ('merchant_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliate_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('merchant_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('LIMITED_STOCK', 'Limited Stock'), ('OUT_OF_STOCK', 'Out Of Stock'), ('COMING_SOON', 'Coming Soon'), ('DISCONTINUED', 'Discontinued')], default='IN_STOCK', max_length=20)),
                ('seller', models.CharField(blank=True, help_text='Specific third-party seller on the merchant platform', max_length=200)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_products', to='affiliate.merchant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_listings', to='products.product')),
            ],
            options={
                'ordering': ['merchant_price'],
                'unique_together': {('product', 'merchant')},
            },
        ),
    ]
