# Generated by Django 5.0.6 on 2026-07-04 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchants/')),
                ('website', models.URLField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('affiliate_supported', models.BooleanField(default=True)),
                ('official_api_supported', models.BooleanField(default=False)),
                ('feed_supported', models.BooleanField(default=False)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('country', models.CharField(default='IN', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority gets synced/searched first')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.CharField(max_length=100)),
                ('tracking_id', models.CharField(blank=True, max_length=100)),
                ('tracking_parameters', models.JSONField(blank=True, default=dict, help_text="e.g. {'tag': 'shopsense-20'}")),
                ('deep_link_base_url', models.URLField(blank=True, max_length=500)),
                ('commission_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('merchant_notes', models.TextField(blank=True, help_text='TOS notes or commission rates')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_account', to='affiliate.merchant')),
            ],
        ),
    ]
