# Generated by Django 5.0.6 on 2026-07-04 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant_products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_url', models.TextField()),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=200)),
                ('browser', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('merchant_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant_products.merchantproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-click_time'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.CharField(help_text='e.g. shopsense-20', max_length=100)),
                ('tracking_param_name', models.CharField(default='tag', help_text='e.g. tag or aff_id', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_config', to='stores.store')),
            ],
        ),
    ]
