# Generated by Django 5.0.6 on 2026-07-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='language',
            field=models.CharField(default='en-IN', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
    ]
