# Generated by Django 5.0.6 on 2026-07-04 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('availability_status', models.CharField(max_length=20)),
                ('seller_rating_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('delivery_charge_snapshot', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cashback_snapshot', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='merchant_products.merchantproduct')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['merchant_product', '-recorded_at'], name='price_track_merchan_a10f2b_idx')],
            },
        ),
    ]
