# Generated by Django 5.0.6 on 2026-07-04 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the feed (e.g. 'Amazon Summer Electronics')", max_length=255)),
                ('feed_type', models.CharField(choices=[('CSV', 'CSV Feed'), ('XML', 'XML Feed'), ('JSON', 'JSON Feed'), ('REST', 'REST API'), ('GRAPHQL', 'GraphQL API'), ('ZIP', 'Compressed Feed (.zip)')], default='CSV', max_length=20)),
                ('feed_url', models.URLField(max_length=2000)),
                ('auth_type', models.CharField(choices=[('NONE', 'No Authentication'), ('BASIC', 'Basic Auth (Username/Password)'), ('BEARER', 'Bearer Token'), ('API_KEY', 'API Key')], default='NONE', max_length=20)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PAUSED', 'Paused'), ('ERROR', 'Error State')], default='INACTIVE', max_length=20)),
                ('sync_frequency', models.IntegerField(default=1440, help_text='Sync frequency in minutes (default 24h)')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('next_sync', models.DateTimeField(blank=True, null=True)),
                ('total_products', models.IntegerField(default=0)),
                ('imported_products', models.IntegerField(default=0)),
                ('failed_products', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='affiliate.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantFeedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PAUSED', 'Paused'), ('ERROR', 'Error State')], max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Time taken to fetch feed in ms', null=True)),
                ('total_products', models.IntegerField(default=0)),
                ('imported_products', models.IntegerField(default=0)),
                ('failed_products', models.IntegerField(default=0)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='merchant_feeds.merchantfeed')),
            ],
            options={
                'verbose_name_plural': 'Merchant feed histories',
            },
        ),
    ]
