# Generated by Django 5.0.6 on 2026-07-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_clicks', models.IntegerField(default=0)),
                ('unique_clicks', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MerchantAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_clicks', models.IntegerField(default=0)),
                ('unique_clicks', models.IntegerField(default=0)),
                ('device_desktop', models.IntegerField(default=0)),
                ('device_mobile', models.IntegerField(default=0)),
                ('device_tablet', models.IntegerField(default=0)),
                ('country_distribution', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlatformEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SEARCH', 'Search'), ('PRODUCT_VIEW', 'Product View'), ('WISHLIST_ADD', 'Wishlist Add'), ('AI_QUERY', 'AI Query'), ('COMPARE', 'Compare'), ('AFFILIATE_CLICK', 'Affiliate Click')], max_length=50)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(default=0)),
                ('search_count', models.IntegerField(default=0)),
                ('comparison_count', models.IntegerField(default=0)),
                ('wishlist_count', models.IntegerField(default=0)),
                ('affiliate_clicks', models.IntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=2, default=0.0, help_text='Click Through Rate (%)', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
