# Generated by Django 5.0.6 on 2026-07-04 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SEARCH', 'Search'), ('PRODUCT_VIEW', 'Product View'), ('WISHLIST_ADD', 'Wishlist Add'), ('AI_QUERY', 'AI Query'), ('COMPARE', 'Compare'), ('AFFILIATE_CLICK', 'Affiliate Click')], max_length=50)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_p_event_t_9b98a9_idx')],
            },
        ),
    ]
