# Generated by Django 5.0.6 on 2026-07-04 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0001_initial'),
        ('analytics', '0001_initial'),
        ('products', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignanalytics',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='tracking.campaign'),
        ),
        migrations.AddField(
            model_name='merchantanalytics',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='affiliate.merchant'),
        ),
        migrations.AddField(
            model_name='platformevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productanalytics',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignanalytics',
            unique_together={('campaign', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='merchantanalytics',
            unique_together={('merchant', 'date')},
        ),
        migrations.AddIndex(
            model_name='platformevent',
            index=models.Index(fields=['event_type', 'created_at'], name='analytics_p_event_t_9b98a9_idx'),
        ),
    ]
