server {
    listen 80;
    server_name shopsense.com www.shopsense.com;
    
    # Redirect all HTTP requests to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name shopsense.com www.shopsense.com;

    # SSL Settings
    ssl_certificate /etc/letsencrypt/live/shopsense.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shopsense.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Security Headers
    add_header X-Frame-Options "DENY";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    # Let S3 handle static files in production, but if local:
    # location /static/ {
    #     root /var/www/shopsense;
    # }
    
    # location /media/ {
    #     root /var/www/shopsense;
    # }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
