# Generated by Django 5.0.6 on 2026-07-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
