[program:celery]
command=/home/ubuntu/SHOPSENSE_Ai_ecommerce/.venv/bin/celery -A shopsense worker -l INFO
directory=/home/ubuntu/SHOPSENSE_Ai_ecommerce
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/celery/worker.log
environment=DJANGO_SETTINGS_MODULE="shopsense.settings.prod"
