# Generated by Django 5.0.6 on 2026-07-04 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankoffer',
            name='store',
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_offers', to='affiliate.merchant'),
        ),
    ]
