# Generated by Django 5.0.6 on 2026-07-04 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0001_initial'),
        ('merchant_feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Duration of the import in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='merchant_feeds.merchantfeed')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='affiliate.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField(help_text='Raw JSON or row data that failed')),
                ('error_reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_errors', to='merchant_sync.merchantimportjob')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='merchant_sync.merchantimportjob')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='affiliate.merchant')),
            ],
        ),
    ]
