# Generated by Django 5.0.6 on 2026-07-04 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255, unique=True)),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('last_results_count', models.PositiveIntegerField(default=0)),
                ('last_searched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-search_count', '-last_searched_at'],
            },
        ),
    ]
