# Generated by Django 5.0.6 on 2026-07-04 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0001_initial'),
        ('merchant_products', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_identifier', models.CharField(help_text='Anonymous session UUID or token', max_length=100, unique=True)),
                ('visitor_identifier', models.CharField(blank=True, help_text='Long-lived visitor cookie', max_length=100, null=True)),
                ('entry_page', models.URLField(blank=True, max_length=1000, null=True)),
                ('exit_page', models.URLField(blank=True, max_length=1000, null=True)),
                ('pages_viewed', models.IntegerField(default=0)),
                ('session_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('clicks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UTMSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.utmsource')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_url', models.TextField(help_text='The final URL with our affiliate parameters')),
                ('original_merchant_url', models.TextField(help_text='The base URL of the merchant product')),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, help_text='Mobile, Tablet, Desktop', max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('referrer', models.TextField(blank=True)),
                ('click_timestamp', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='affiliate.merchant')),
                ('merchant_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='merchant_products.merchantproduct')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_clicks', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='tracking.campaign')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='tracking.clicksession')),
            ],
            options={
                'ordering': ['-click_timestamp'],
                'indexes': [models.Index(fields=['merchant', 'click_timestamp'], name='tracking_af_merchan_99ea2c_idx'), models.Index(fields=['product', 'click_timestamp'], name='tracking_af_product_aac707_idx'), models.Index(fields=['session', 'click_timestamp'], name='tracking_af_session_ea32be_idx')],
            },
        ),
    ]
