# Generated by Django 5.0.6 on 2026-07-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ShopSense AI', max_length=100)),
                ('default_title', models.CharField(max_length=200)),
                ('default_description', models.TextField()),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UrlRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='e.g. /old-product/', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='e.g. /products/new-product/', max_length=255)),
                ('is_permanent', models.BooleanField(default=True, help_text='Use 301 for permanent, 302 for temporary')),
            ],
        ),
    ]
